booktime/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls')),
    path("__reload__/", include('django_browser_reload.urls'))
]

main/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'main'

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name='home'),
    path("about-us/", TemplateView.as_view(template_name="about_us.html"), name='about_us'),


]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.

main/templates/about_us.html
{% extends 'base.html' %}


{% block content %}
    <h2>About Us</h2>
    <p>BookTime is a company that sells books online.</p>
{% endblock content %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>BookTime</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="/" class="navbar-brand">BookTime</a>
        <button 
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"
            id="navbarSupportedContent">
        </div>
            <ul class="navbar-nav mr-auto">
                <li 
                    class=nav-item {% if request.path == "/" %}active{% endif %}>
                    <a href="{% url 'main:home' %}" class="nav-link">Home</a>
                </li>
                <li 
                    class="nav-item {% if request.path == "/about-us/" %}active{% endif %}">
                    <a href="{% url 'main:about_us' %}" class="nav-link">About Us</a>
                </li>
            </ul>
    </nav>
    {% block content %}
    {% endblock content %}
    <script src="{% static 'js/jquery.min.js' %} "></script>
    <script src="{% static 'js/popper.min.js' %} "></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

main/templates/home.html
{% extends 'base.html' %}

{% block content %}

    <h2>Home</h2>
    <p>this will be the content of home</p>
{% endblock content %}